# Generated by Django 4.2.1 on 2023-05-31 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_class_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('alt_mobile_no', models.PositiveIntegerField()),
                ('aadhaar_no', models.PositiveBigIntegerField()),
                ('vill_town', models.CharField(max_length=200)),
                ('post_office', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('gaon_panchayat', models.CharField(max_length=200)),
                ('educational_block', models.CharField(max_length=200)),
                ('cluster', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pin', models.PositiveIntegerField()),
                ('registration_no', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=350)),
                ('account_no', models.PositiveIntegerField()),
                ('branch_name', models.CharField(max_length=350)),
                ('ifsc', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(upload_to='media/students/photos')),
                ('dob_certificate', models.ImageField(upload_to='media/students/certificates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.class')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.session')),
            ],
        ),
    ]
