# Generated by Django 4.2.1 on 2023-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_class_created_at_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob_certificate',
            field=models.FileField(upload_to='media/students/certificates'),
        ),
    ]
