# Generated by Django 4.2.1 on 2023-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_student_name_student_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(upload_to='media/profile_pic'),
        ),
    ]
