# Generated by Django 4.2.1 on 2023-06-02 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField()),
                ('sex', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('alt_mobile_no', models.PositiveIntegerField()),
                ('pan_no', models.PositiveBigIntegerField()),
                ('aadhaar_no', models.PositiveBigIntegerField()),
                ('vill_town', models.CharField(max_length=200)),
                ('post_office', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pin', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=350)),
                ('account_no', models.PositiveIntegerField()),
                ('branch_name', models.CharField(max_length=350)),
                ('ifsc', models.CharField(max_length=100)),
                ('teacher_photo', models.ImageField(upload_to='media/profile_pic')),
                ('cv_resume', models.FileField(upload_to='media/teachers/certificates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
