# Generated by Django 4.2.1 on 2023-06-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='alt_mobile_no',
        ),
    ]
