# Generated by Django 4.2.1 on 2023-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_teacher_alt_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
