# Generated by Django 4.2.1 on 2023-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_teacher_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
