# Generated by Django 4.2.1 on 2023-06-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_teacher_allotment_teacher_id_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.class'),
            preserve_default=False,
        ),
    ]
