# Generated by Django 4.2.1 on 2023-06-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_attendance_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_save',
            name='attendance_id',
        ),
    ]
