# Generated by Django 4.2.1 on 2023-06-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_attendance_save_save_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_attendance',
            name='attendance_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.attendance'),
            preserve_default=False,
        ),
    ]
