# Generated by Django 4.2.1 on 2023-06-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_save_attendance_attendance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_attendance',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='save_attendance',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Save_Attendance',
        ),
    ]
