# Generated by Django 4.2.1 on 2023-07-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_study_materials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Study_Materials',
            new_name='Study_Material',
        ),
    ]
