# Generated by Django 4.2.1 on 2023-07-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_study_materials_study_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='teacher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.teacher'),
            preserve_default=False,
        ),
    ]
